server:
  port: 8888
  tomcat:
    uri-encoding: utf-8

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.36:3306/prison?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: justsoso
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1000
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 1 from dual
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 800MB
  aop:
    proxy-target-class: true

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*/**Mapper.xml
  typeAliasesPackage: com.christian.gen.*.entity
  #typeEnumsPackage: com.zhenhan.fund.*.entity.enums
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      table-underline: true
      #capital-mode: true
      logic-delete-value: 2
      logic-not-delete-value: 1
      db-type: MYSQL

    refresh: true

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl